name: Examples

on:
  push:
    branches: [ main ]
    paths:
      - 'README.md'
      - 'examples/**'
      - 'src/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'README.md'
      - 'examples/**'
      - 'src/**'

jobs:
  test-examples:
    name: Test Examples
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - uses: actions/checkout@v4
      
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
      
      - name: Cache cargo registry
        uses: actions/cache@v4
        with:
          path: ~/.cargo/registry
          key: ${{ runner.os }}-cargo-registry-${{ hashFiles('**/Cargo.lock') }}
      
      - name: Build all example binaries
        run: cargo build --bins -p hojicha-examples
      
      - name: Check each example binary individually
        run: |
          for example in examples/src/*.rs; do
            if [ -f "$example" ]; then
              name=$(basename "$example" .rs)
              echo "Checking example binary: $name"
              cargo check --bin "$name" -p hojicha-examples
            fi
          done
        shell: bash